server:
  port: 8801

eureka:
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.1

  instance:
#    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.250.86:${server.port}/eureka/